### PR TITLE
APCu still uses `apc.enabled` and `apc.enable_cli` directives

### PR DESCRIPTION
**Pull request by enov**

### CODE REVIEW

**Comment by enov** [comment]
@neo22s this is locally tested. I think this commit will be available in your PR if you merge.

**Comment by enov** [comment]
Thanks!

For the record, I could not use `apcu_enabled()` (available in v4.0.3+) as I have v4.0.2 of APCu installed locally. So I thought reading from the ini directives would make it have a wider reach.

**Comment by enov** [comment]
@neo22s Do you mind adding me to this repo so that I can make the squashing and any future adjustments needed for the PR to be merged?

Thanks!

**Comment by neo22s** [comment]
done!

**Comment by enov** [comment]
Thanks!

**Comment by enov** [comment]
@neo22s changes are now squashed into a single commit. I guess we should probably wait for @acoulton to review and merge the original PR.

**Pull request merged**
